### PR TITLE
added option to download videos statistics

### PR DESCRIPTION
**Pull request by AntonKorobkov**
'Videos' section instead of 'Tweets'

### CODE REVIEW

**Comment by philippe2803** [comment]
Nice extension. Did you test it properly? Does it work as intended?

**Comment by AntonKorobkov** [comment]
I tested it only manually. Should I unit test it as well? I didn't locate test case for ReportDownloader itself

**Comment by philippe2803** [comment]
Manual test is fine. Unit testing with Selenium are uneasy to deal with.

**Comment by philippe2803** [comment]
Thank you very much @AntonKorobkov !

**Pull request merged**
